GroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('auth/', include('toysrent_auth.urls')),
    path('user/', include('user.urls')),
    path('pesan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
    path('items/', include('item.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('<str:updated>', show_items, name = 'show_items'),
    path('create/', create_item, name = 'create_item'),
    path('update/<str:item_name>/', update_item, name = 'update_item'),
    path('delete/', delete_item, name = 'delete_item'),
]

pesanan/urls.py
from django.urls import path

from pesanan import views

app_name = 'pesanan'

urlpatterns = [
    path('', views.index, name='pesan'),
    path('daftarpesanan/', views.daftar_pesanan, name='daftar_pesanan'),
    path('update/<str:id_pesanan>/', views.update_pesanan),
    path('berhasilpesan', views.berhasil_pesan),
    path('cekharga', views.cek_total_harga, name='cekharga'),

]

pesanan/models.py
# Create your models here.

pesanan/views.py
import datetime
import json

from django.db import connection
from django.http import HttpResponse
from django.shortcuts import render


def admin_get_all_pesanan():
    print("ADMIN>>>")
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM toys_rent.PEMESANAN")
        data = cursor.fetchall()
        cursor.close()

    return data


def anggota_get_all_pesanan(id_user):
    print("ANGGOTA>>>")
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to toys_rent;")
        cursor.execute("SELECT * FROM PEMESANAN WHERE no_ktp_pemesan = '{}';".format(id_user))
        data = cursor.fetchall()
        cursor.close()

    return data


def get_barang_from_id_pesanan(id_pesanan):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO toys_rent;")
        cursor.execute("SELECT B.id_barang, B.nama_item FROM PEMESANAN P, BARANG_PESANAN BP, BARANG B " +
                       "WHERE P.id_pemesanan = BP.id_pemesanan AND B.id_barang = BP.id_barang " +
                       "AND P.id_pemesanan = '{}';".format(id_pesanan))

        print("= AFTER QUERY")  # LOG
        data = cursor.fetchall()
        cursor.close()

    return data


def berhasil_pesan(request):
    idn = request.session.get('idn')
    now = datetime.datetime.now()
    tanggal = now.strftime("%Y-%m-%d %H:%M")

    if request.method == 'POST':
        data = json.loads(request.POST['pesanan'])
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO toys_rent;")
            cursor.execute("SELECT id_pemesanan FROM PEMESANAN ORDER BY id_pemesanan DESC")
            id_pemesanan = int(cursor.fetchone()[0]) + 1

        kuantitas_barang = str(len(data))
        totalnya = request.POST['total_harga']

        print("<<< LOG >>>")

        print(id_pemesanan)
        # print("TOTALLLLLLLLALAALSDLALSDASLD")
        # print(totalnya)

        ####
        print(request.POST['pesanan'])
        semua = request.POST['pesanan']
        semua = json.loads(semua)

        ####

        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO toys_rent;")
            cursor.execute(
                "INSERT INTO PEMESANAN VALUES ('{}', '{}', {}, {}, {}, '{}','{}');".format(id_pemesanan, tanggal,
                                                                                           kuantitas_barang, totalnya,
                                                                                           1234, idn, 'Mauv'))
        for i in semua:
            print(i[1])
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO toys_rent;")
                cursor.execute("SELECT COUNT(*) FROM BARANG_PESANAN;")
                jumlah = cursor.fetchone()[0] + 1
                cursor.execute(
                    "INSERT INTO BARANG_PESANAN VALUES ('{}', {}, '{}', '2019-05-28', 2, '2019-05-30', 'Mauv')".format(
                        id_pemesanan, jumlah, i[1]))
                cursor.close()

        return HttpResponse("Berhasil POST")
    else:

        return render(request, 'berhasilpesan.html')


def get_all_barang():
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO toys_rent;")
        cursor.execute("SELECT * FROM BARANG;")
        all_barang = cursor.fetchall()
        return all_barang


def get_all_user():
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO toys_rent;")
        cursor.execute("SELECT P.nama_lengkap, P.no_ktp FROM ANGGOTA A, PENGGUNA P WHERE P.no_ktp = A.no_ktp;")
        all_anggota = cursor.fetchall()
        return all_anggota


# Create your views here.
def index(request):
    role = request.session.get('role')
    idn = request.session.get('idn')
    print("role : " + role)
    all_barang = get_all_barang()
    all_anggota = get_all_user()

    context = {
        'all_barang': all_barang,
        'all_anggota': all_anggota,
        'idn': idn,
        'role': role

    }
    return render(request, 'pemesanan.html', context)


def get_harga_of_barang(id_barang):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO toys_rent")
        cursor.execute(
            "SELECT harga_sewa FROM INFO_BARANG_LEVEL NATURAL JOIN BARANG WHERE id_barang = '{}';".format(
                id_barang))
        hasil = cursor.fetchone()[0]
    return hasil


def cek_total_harga(request):
    if request.method == 'POST':
        print(request.POST['pesanan'])
        semua = request.POST['pesanan'].split(",")
        total = 0

        # for i in semua:
        #     print(i)
        #     print(get_harga_of_barang(i))

        for i in range(len(semua) - 1):
            harga = get_harga_of_barang(semua[i])
            print(harga)
            total += int(harga)

        print("TOTAL")
        print(str(total))

        return HttpResponse(total)


def daftar_pesanan(request):
    if request.method == 'POST':
        id_pesanan = request.POST['id_pesanan']
        print(id_pesanan)

        with connection.cursor() as cursor:
            cursor.execute("SET search_path TO toys_rent")
            cursor.execute("DELETE FROM PEMESANAN WHERE LOWER(id_pemesanan) = LOWER('{}');".format(id_pesanan))
        return HttpResponse('SUCCESS')
    else:
        low = 0
        high = 0

        role = request.session.get('role')
        idn = request.session.get('idn')
        print('role: ' + role)
        if role == 'admin':
            semua_pesanan = admin_get_all_pesanan()
        elif role == 'member':
            semua_pesanan = anggota_get_all_pesanan(idn)
        else:
            return HttpResponse('<h3>gaboleh buka kalo belom login<h3>')

        for i in range(len(semua_pesanan)):
            semua_pesanan[i] += (get_barang_from_id_pesanan(semua_pesanan[i][0]),)

        context = {
            'semua_pesanan': semua_pesanan,
            'idn': idn,
            'role': role

        }
        return render(request, 'daftar-pesanan.html', context)


def update_pesanan(request, id_pesanan):
    if request.method == 'POST':
        if request.POST['command'] == 'TAMBAH':
            print('>> ' + request.POST['the_barang'])
            id_barang = request.POST['the_barang'].split(',')[0][2:-1]

            print('<<< ' + id_barang)

            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO toys_rent;")
                cursor.execute("SELECT COUNT(*) FROM BARANG_PESANAN;")
                jumlah = cursor.fetchone()[0] + 1
                cursor.execute(
                    "INSERT INTO BARANG_PESANAN VALUES ('{}', {}, '{}', '2019-05-28', 2, '2019-05-30', 'Puce')".format(
                        id_pesanan, jumlah, id_barang))
                cursor.close()

            return HttpResponse('success TAMBAH')
        elif request.POST['command'] == 'DELETE':
            id_barang = request.POST['the_barang']
            print(id_barang)
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO toys_rent;")
                cursor.execute(
                    "DELETE FROM BARANG_PESANAN WHERE id_barang = '{}' AND id_pemesanan = '{}';".format(id_barang,
                                                                                                        id_pesanan))
            cursor.close()

            return HttpResponse('success DELETE')

    else:
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO toys_rent;")
            cursor.execute("SELECT * FROM BARANG")
            barang = cursor.fetchall()
            cursor.close()

        data = get_barang_from_id_pesanan(id_pesanan)

        context = {
            'data': data,
            'barang': barang,
        }
        print(data)
        return render(request, 'update-pesanan.html', context)

pesanan/templates/berhasilpesan.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta http-equiv="refresh"
          content="3; url=/pesan/daftarpesanan">

    <meta charset="UTF-8">
    <title>Berhasil Pesan</title>
</head>
<body>
{% if role == "admin" %}
    {% include 'navbar_admin.html' %}
{% else %}
    {% include 'navbar_anggota.html' %}
{% endif %}
Pesan Berhasil Ditambahkan <br>
Akan auto redirect dalam 3 detik


</body>
</html>

pesanan/templates/daftar-pesanan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daftar Pesanan</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>


</head>
<body>
{% if role == "admin" %}
    {% include 'navbar_admin.html' %}
{% else %}
    {% include 'navbar_anggota.html' %}
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h3>Daftar Pesanan</h3>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Id pesanan</th>
                    <th scope="col">Daftar barang</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                    <th scope="col">Action(Admin)</th>
                </tr>
                </thead>
                <tbody>

                {% for pesanan in semua_pesanan %}
                    <tr>
                        <th scope="row">{{ pesanan.0 }}</th>
                        <td>{{ pesanan.7 }}</td>
                        <td>{{ pesanan.3 }}</td>
                        <td>{{ pesanan.6 }}</td>
                        <td>
                            <button onclick="updateFunction({{ pesanan.0 }})">UPDATE</button>
                        </td>
                        <td>
                            <button onclick="deleteFunction({{ pesanan.0 }})">DELETE</button>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

            <h3>Filter Harga</h3>
            <form>
                {% csrf_token %}
                <div class="form-group">

                    <label for="formGroupExampleInput">Dari</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="100">
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Sampai</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="500">
                </div>
            </form>


        </div>
    </div>
</div>

<script>
    function updateFunction(idPesanan) {
        window.location.href = "/pesan/update/" + idPesanan + "/";
    }

    function deleteFunction(idPesanan) {
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();

        $.ajax({
            type: 'POST',
            url: '',
            data: {'id_pesanan': idPesanan},
            headers: {
                "X-CSRFToken": csrftoken
            },
            success: function (data) {
                alert('Pesanan berhasil dihapus');
                location.reload();


            },
            error: function (sesuatu) {
                alert('error');
            }


        });
    }

</script>

</body>
</html>

pesanan/templates/pemesanan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pesan</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>


</head>
<body>
{% if role == "admin" %}
    {% include 'navbar_admin.html' %}
{% else %}
    {% include 'navbar_anggota.html' %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h3>Barang Yang Dipilih : </h3>
            <ul id="list-barang">


            </ul>

            <div class="form-group">

                {% csrf_token %}
                <!--Admin Only-->
                <label for="anggotaSelect">Anggota: </label>
                <select class="form-control" id="anggotaSelect">
                    {% for anggota in all_anggota %}
                        <option id="{{ anggota.1 }}">{{ anggota.0 }}</option>
                    {% endfor %}
                </select>


                <label for="sel1">Barang:</label>
                <select class="form-control" id="barang_dipilih">
                    {% for barang in all_barang %}
                        <option id="{{ barang.0 }}">{{ barang.1 }}</option>
                    {% endfor %}

                </select>
                <button onclick="tambahKeList()" type="button">Pilih barang</button>
                <br>

                <label for="hari">Berapa lama?</label>
                <input type="number" name="amount" class="form-control" placeholder="masukan jumlah hari" step="any"
                       required="" id="hari">
                <br>
                {#                <button class="btn btn-primary" type="submit" onclick="pesan()">Pesan</button>#}
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                        onclick="pesan()">
                    Pesan
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Total Harga : <h4 id="total-harga">Loading Total... Harap Menunggu</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button id="lanjut" type="button" class="btn btn-primary" onclick="lanjut()" disabled>Lanjut?</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- -->

            </div>


        </div>
    </div>
</div>

<script>


    function tambahKeList() {

        var barangDipilih = $("#barang_dipilih").val();
        var idBarang = $("#barang_dipilih").children(":selected").attr("id");
        $("#list-barang").append($("<li id=\"" + idBarang + "\">" + barangDipilih + "</li>"));
    }

    function pesan() {
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();

        var idBarang = "";
        $('#list-barang li').each(function (i) {
            //var dalemArray = [];
            //dalemArray.push($(this).attr("id"));
            //array.push(dalemArray);
            idBarang += $(this).attr("id") + ',';
        });

        alert(idBarang);
        $.ajax({
            type: 'POST',
            url: '{% url 'pesanan:cekharga' %}',
            data: {'pesanan': idBarang},
            headers: {
                "X-CSRFToken": csrftoken
            },
            success: function (data) {

                $("#total-harga").html(data);
                $("#lanjut").prop("disabled", false);


            },
            error: function (sesuatu) {
                alert('error');
            }


        });


    }

    function lanjut() {


        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        var array = [];// del
        $('#list-barang li').each(function (i) {
            var dalemArray = [];

            dalemArray.push($(this).text());
            dalemArray.push($(this).attr("id"));
            array.push(dalemArray);
        }); //del


        $.ajax({
            type: 'POST',
            url: '/pesan/berhasilpesan',
            data: {'pesanan': JSON.stringify(array), 'total_harga' : $('#total-harga').text()},
            headers: {
                "X-CSRFToken": csrftoken
            },
            success: function (data) {
                alert(array);
                location.reload();


            },
            error: function (sesuatu) {
                alert('error');
            }


        });
    }


</script>

</body>
</html>

pesanan/templates/update-pesanan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update pesanan</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>


</head>
<body>
{% if role == "admin" %}
    {% include 'navbar_admin.html' %}
{% else %}
    {% include 'navbar_anggota.html' %}
{% endif %}
{% csrf_token %}

<h3>Barang:</h3>
<ul>
    {% for barang in data %}
        <li>{{ barang.1 }}
            <button onclick="deleteFunction({{ barang.0 }})">Delete</button>
        </li>
    {% endfor %}


</ul>

<div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="pilih_barang">
        {% for item in barang %}
            <option>{{ item }}</option>
        {% endfor %}
    </select>

    <button onclick="tambahFunction()">Tambah</button>
</div>

<br>
<button>UPDATE</button>

<script>

    function deleteFunction(id_barang) {
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        $.ajax({
            type: 'POST',
            url: '',
            data: {'command': 'DELETE', 'the_barang': id_barang},
            headers: {
                "X-CSRFToken": csrftoken
            },
            success: function (data) {
                alert('Berhasil HAPUS');
                location.reload();


            },
            error: function (sesuatu) {
                alert('error');
            }


        });
    }

    function tambahFunction() {
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        $.ajax({
            type: 'POST',
            url: '',
            data: {'command': 'TAMBAH', 'the_barang': $('#pilih_barang').val()},
            headers: {
                "X-CSRFToken": csrftoken
            },
            success: function (data) {
                alert('Berhasil Tambah');
                location.reload();


            },
            error: function (sesuatu) {
                alert('error');
            }


        });

    }


</script>

</body>
</html>