GroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('auth/', include('toysrent_auth.urls')),
    path('user/', include('user.urls')),
    path('pesan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
    path('items/', include('item.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('<str:updated>', show_items, name = 'show_items'),
    path('create/', create_item, name = 'create_item'),
    path('update/<str:item_name>/', update_item, name = 'update_item'),
    path('delete/', delete_item, name = 'delete_item'),
]

level/urls.py
from django.urls import path

from . import views

app_name = 'level'

urlpatterns = [
    path('', views.index, name='daftar_level'),
    path('tambah', views.tambah_level, name='tambah'),
    path('update/<str:nama_level>/', views.update_level_page),
    path('update/', views.update_post_handler, name='update'),

]

pesanan/urls.py
from django.urls import path

from pesanan import views

app_name = 'pesanan'

urlpatterns = [
    path('', views.index, name='pesan'),
    path('daftarpesanan/', views.daftar_pesanan, name='daftar_pesanan'),
    path('update/<str:id_pesanan>/', views.update_pesanan),
    path('berhasilpesan', views.berhasil_pesan),
    path('cekharga', views.cek_total_harga, name='cekharga'),

]

review/urls.py
from django.urls import path
from .views import *

app_name = 'review'

urlpatterns = [
    path('buat-review/', buat_review, name = 'buat-review'),
    path('buat-review/<str:no_resi>', buat_review),
    path('update-review/<str:no_resi>/<str:no_urut>', update_review),
    path('update-review/', update_review_post_handler, name = 'update-review'),
    path('daftar-review/', daftar_review, name = 'daftar-review'),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('profile/', profile, name = 'profile'),

]

templates/navbar_admin.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand blue-under font-title" href="#">ToysRent</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>        
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Item
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'item:create_item' %}">Tambah Item</a>
                <a class="dropdown-item" href="{% url 'item:show_items' "static" %}">Daftar Item</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Barang
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Tambah Barang</a>
                <a class="dropdown-item" href="#">Daftar Barang</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Level
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'level:tambah' %}">Tambah Level</a>
                <a class="dropdown-item" href="{% url 'level:daftar_level' %}">Daftar Level</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                a class="dropdown-item" href="{% url 'pesanan:pesan' %}">Buat Pesanan</a>
                <a class="dropdown-item" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pengiriman
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'pengiriman:buat-pengiriman' %}">Buat Pengiriman</a>
                    <a class="dropdown-item" href="{% url 'pengiriman:daftar-pengiriman' %}">Daftar Pengiriman</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}">Profile <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Chat Pengguna</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Daftar Review</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toysrent_auth:login' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

templates/navbar_anggota.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand blue-under font-title" href="#">ToysRent</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>        
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'item:show_items' "static" %}">Daftar Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Daftar Barang</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Level
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'level:daftar_level' %}">Daftar Level</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'pesanan:pesan' %}">Buat Pesanan</a>
                <a class="dropdown-item" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pengiriman
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'pengiriman:buat-pengiriman' %}">Buat Pengiriman</a>
                <a class="dropdown-item" href="{% url 'pengiriman:daftar-pengiriman' %}">Daftar Pengiriman</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}">Profile <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Chat Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'review:daftar-review' %}">Daftar Review</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toysrent_auth:login' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>