GroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('auth/', include('toysrent_auth.urls')),
    path('user/', include('user.urls')),
    path('pesan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
    path('items/', include('item.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('<str:updated>', show_items, name = 'show_items'),
    path('create/', create_item, name = 'create_item'),
    path('update/<str:item_name>/', update_item, name = 'update_item'),
    path('delete/', delete_item, name = 'delete_item'),
]

item/models.py
from django.db import models

# Create your models here.
class Kategori(models.Model):
    nama = models.CharField(max_length=100, primary_key=True)
    level = models.IntegerField()
    sub = models.ForeignKey("Kategori", on_delete= models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Kategori"

    def __str__(self):
        return self.nama

    def __unicode__(self):
        return self.nama

item/forms.py
from django import forms
from .models import Kategori


class MyModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.nama

class ItemForm(forms.Form):
    nama = forms.CharField(label = "Nama", max_length = 50, widget = forms.TextInput(
        attrs = {
            "required" : True,
            "class" : "form-control",
            "placeholder" : "Nama Item"
        }
    ))
    deskripsi = forms.CharField(label = "Deskripsi", max_length = 50, widget = forms.Textarea(
        attrs = {
            "rows":"5",
            "required" : True,
            "class" : "form-control",
            "placeholder" : "Deskripsi"
        }
    ))
    usia_awal = forms.FloatField(label = "", widget = forms.NumberInput(
        attrs = {
            "required" : True,
            "class" : "form-control-1",
            "placeholder" : "Usia Awal"
        }
    ))
    usia_akhir = forms.FloatField(label = "", widget = forms.NumberInput(
        attrs = {
            "required" : True,
            "class" : "form-control-1",
            "placeholder" : "Usia Akhir"
        }
    ))
    bahan = forms.CharField(label = "Bahan", max_length = 50, widget = forms.TextInput(
        attrs = {
            "required" : True,
            "class" : "form-control",
            "placeholder" : "Bahan"
        }
    ))
    kategori = MyModelMultipleChoiceField(
        queryset = Kategori.objects.all(),
        label = "Kategori",
        widget = forms.SelectMultiple(
            attrs = {
                "class": "selectpicker form-control",
                "placeholder" : "Kategori",
                "multiple": "multiple",
                "data-live-search": "true"
            }
        )
    )

item/views.py
from django.db import connection
from django.http import JsonResponse
from django.shortcuts import render, redirect
import psycopg2
import json

from .forms import ItemForm

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def get_items():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.item")
        return dictfetchall(control)

def get_item(idn):
    with connection.cursor() as control:
        control.execute("select * from toys_rent.item where nama = %s", (idn,))
        return dictfetchall(control)

def get_item_categories():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.kategori_item")
        return dictfetchall(control)

def get_item_category(idn):
    with connection.cursor() as control:
        control.execute("select * from toys_rent.kategori_item where nama_item = %s", (idn,))
        return dictfetchall(control)

def get_categories():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.kategori")
        return dictfetchall(control)

def show_items(req, updated):
    if 'role' not in req.session:
        return redirect("toysrent_auth:login")
        
    items = get_items()
    item_categories = get_item_categories()

    for item in items:
        item['kategori'] = []

    for item_category in item_categories:
        for item in items:
            if item_category['nama_item'] == item['nama']:
                item['kategori'].append(item_category['nama_kategori'])
                break
        
    if updated == "new":
        updated = True
    else:
        updated = False

    return render(req, 'items.html', {"role" : req.session['role'], "items" : items, "updated": updated})

def create_item(req):
    if 'role' not in req.session:
        return redirect("toysrent_auth:login")
    
    if req.session['role'] != "admin":
        return redirect("user:profile")

    if req.method == 'POST':
        dict_req = dict(req.POST)
        
        with connection.cursor() as control:
            control.execute("insert into toys_rent.item(nama, deskripsi, usia_dari, usia_sampai, bahan)" +
                            "values(%s,%s,%s,%s,%s)",
                            (dict_req['nama'][0], dict_req['deskripsi'][0], int(dict_req['usia_awal'][0]), int(dict_req['usia_akhir'][0]), dict_req['bahan'][0],))
            
            for kategori in dict_req['kategori']:
                control.execute("insert into toys_rent.kategori_item(nama_item, nama_kategori) values(%s, %s)", (dict_req['nama'][0], kategori,))

        return redirect('item:show_items', updated = "new")

    else:
        form_tambah_item = ItemForm()
        return render(req, 'create.html', {"role" : req.session['role'], 'form_tambah_item' : form_tambah_item})

def delete_item(req):
    if 'role' not in req.session:
        return redirect("toysrent_auth:login")
    
    if req.session['role'] != "admin":
        return redirect("user:profile")

    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)

        with connection.cursor() as control:
            control.execute("delete from toys_rent.item where nama = %s", (data['item_name'],))
        
        return JsonResponse({'success': True})

def update_item(req, item_name):
    if 'role' not in req.session:
        return redirect("toysrent_auth:login")
    
    if req.session['role'] != "admin":
        return redirect("user:profile")
        
    if req.method == 'GET':
        # init_categories()
        item_data = get_item(item_name)
        item_categories = get_item_category(item_name)

        item_data[0]['kategoriT'] = []

        for item_category in item_categories:
            item_data[0]['kategoriT'].append(item_category['nama_kategori'])

        form_update_item = ItemForm(initial =
            {
                'nama' : item_name,
                'deskripsi' : item_data[0]['deskripsi'],
                'usia_awal' : item_data[0]['usia_dari'],
                'usia_akhir' : item_data[0]['usia_sampai'],
                'bahan' : item_data[0]['bahan'],
                'kategori': item_data[0]['kategoriT']
            }
        )

        return render(req, 'update.html', {"role" : req.session['role'], 'form_update_item' : form_update_item})
    else:
        dict_req = dict(req.POST)
        item_categories = get_item_category(item_name)

        with connection.cursor() as control:
            control.execute("update toys_rent.item set nama=%s, deskripsi=%s, usia_dari=%s, usia_sampai=%s, bahan=%s where nama=%s",
                            (item_name, req.POST['deskripsi'], int(req.POST['usia_awal']), int(req.POST['usia_akhir']), req.POST['bahan'], item_name,))
        
            found = False
            for kategori in dict_req['kategori']:
                found = False
                for item_category in item_categories:
                    if kategori in item_category.values():
                        found = True
                if not found:
                    control.execute("insert into toys_rent.kategori_item(nama_item, nama_kategori) values(%s, %s)", (item_name, kategori,))
            
            for item_category in item_categories:
                if item_category['nama_kategori'] not in dict_req['kategori']:
                    control.execute("delete from toys_rent.kategori_item where nama_item=%s and nama_kategori=%s", (item_name, item_category['nama_kategori'],))
        
        return redirect('item:show_items', updated = "new")
                    

            

item/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Item</title>
    <link rel = "stylesheet" href = "{% static 'item/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
</head>
<body class="bg-light main">
    <div class="container">
        {% if role == "admin" %}
            {% include 'navbar_admin.html' %}
        {% else %}
            {% include 'navbar_anggota.html' %}
        {% endif %}
        <div class = "display-4 banner">
            Tambah Item
            <hr>
        </div>
        <div class="item-area">
            <div class = "reg-content" id="reg-content-item">
                <form method="POST", action="", class = "login-form" id = "form-1">
                    {% csrf_token %}
                    {{ form_tambah_item.nama }}
                    {{ form_tambah_item.deskripsi }}
                    {{ form_tambah_item.usia_awal }}&nbsp;-&nbsp; {{ form_tambah_item.usia_akhir }}
                    {{ form_tambah_item.bahan }}
                    {{ form_tambah_item.kategori }}
                    <button class = "btn btn-outline-dark submit"type="submit">Tambah Item</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('select').selectpicker();
            $('.filter-option-inner-inner').html("Kategori");
        });
    </script>
</body>
</html>

item/templates/items.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Item</title>
    <link rel = "stylesheet" href = "{% static 'item/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- MDB core JavaScript -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src = "{% static 'mdb/js/mdb.min.js' %}" type = "text/javascript"></script>
    <link rel = "stylesheet" href = "{% static 'mdb/css/addons/datatables.min.css' %}">
    <script src = "{% static 'mdb/js/addons/datatables.min.js' %}" type = "text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src = "{% static 'item/js/scripts.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'toysrent_auth/js/accordion.js' %}" type = "text/javascript"></script>
</head>
<body class = "bg-light main">
    <div class = "container">
        {% if role == "admin" %}
            {% include 'navbar_admin.html' %}
        {% else %}
            {% include 'navbar_anggota.html' %}
        {% endif %}
        <div class = "display-4 banner">
            Daftar Item
            <hr>
        </div>
        {% if updated %}
            <h6 style="color:rgb(17, 162, 17)">Item telah terupdate!</h6>
        {% endif %}
        <h5>Klik salah satu atribut untuk mensortir.</h5>
        <table class="table table-striped" id="dtItem">
            <thead>
                <tr>
                    <th class ="th-sm" scope = "col">No.</th>
                    <th class ="th-sm" scope = "col">Nama</th>
                    <th class ="th-sm" scope = "col">Kategori</th>
                    <th class ="th-sm" scope = "col">Action</th>
                    {% if role == "admin" %}
                        <th class ="th-sm" scope = "col">Action [ADMIN]</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr scope = "row" id = "row-{{forloop.counter}}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.nama }}</td>
                        <td>
                            {% for kategori in item.kategori %}
                                {{ kategori }},
                            {% endfor %}
                        </td>
                        <td><a class = "blue-under table-ref" href = "#">Lihat Barang-barang</a></td>
                        {% if role == "admin" %}
                            <td class = "identifier" id = "{{ item.nama }}">
                                <!-- Bikin id untuk update item -->
                                {% csrf_token %}
                                <a class = "blue-under table-ref"  href = "{% url 'item:update_item' item.nama %}">Update</a>
                                <span class = "separator">|</span> 
                                <a class = "blue-under table-ref" href = "#" data-toggle="modal" data-target="#deleteModal-{{forloop.counter}}">Delete</a> 
                                <span class = "separator">|</span> 
                                <a class = "blue-under table-ref" href = "#">Tambah Barang</a>
                            </td>
                            <div class="modal fade" id="deleteModal-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="modalLabel">Delete Item?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Apakah anda benar-benar ingin menghapus item ini?
                                        <br>
                                        Semua barang dan pemesanan yang dimiliki item ini akan ikut terhapus!
                                    </div>
                                    <div class="modal-footer">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="button" id = "delete-{{ forloop.counter }}-{{ item.nama }}" onClick="deleteItem(this)" class="btn btn-outline-danger" data-dismiss="modal">Delete Item</button>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </tr>
                {% endfor %}
                
            </tbody>
            <button id="after-modal" data-toggle="modal" data-target="#delete-after" style="display:none"></button>
            <div class="modal fade" id="delete-after" tabindex="-1" role="dialog" aria-labelledby="modalLabel2" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel2">Item Terhapus!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Item telah dihapus!
                    </div>
                    <div class="modal-footer">
                        {% csrf_token %}
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                        <a href = "{% url 'item:show_items' "new" %}" class="btn btn-outline-primary">Refresh Page</a>
                    </div>
                    </div>
                </div>
            </div>
        </table>

    </div>
</body>
</html>

item/templates/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Item</title>
    <link rel = "stylesheet" href = "{% static 'item/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
</head>
<body class="bg-light main">
    <div class="container">
        {% if role == "admin" %}
            {% include 'navbar_admin.html' %}
        {% else %}
            {% include 'navbar_anggota.html' %}
        {% endif %}
        <div class = "display-4 banner">
            Update Item
            <hr>
        </div>
        <div class="item-area">
            <div class = "reg-content" id="reg-content-item">
                <form method="POST", action="", class = "login-form" id = "form-1">
                    {% csrf_token %}
                    {{ form_update_item.nama }}
                    {{ form_update_item.deskripsi }}
                    {{ form_update_item.usia_awal }}&nbsp;-&nbsp; {{ form_update_item.usia_akhir }}
                    {{ form_update_item.bahan }}
                    {{ form_update_item.kategori }}
                    <button class = "btn btn-outline-dark submit"type="submit">Update Item</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('select').selectpicker();
            $('.filter-option-inner-inner').html("Kategori");
            $('#id_nama').attr("readonly", "readonly")
        });
    </script>
</body>
</html>