GroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('auth/', include('toysrent_auth.urls')),
    path('user/', include('user.urls')),
    path('pesan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
    path('items/', include('item.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('<str:updated>', show_items, name = 'show_items'),
    path('create/', create_item, name = 'create_item'),
    path('update/<str:item_name>/', update_item, name = 'update_item'),
    path('delete/', delete_item, name = 'delete_item'),
]

toysrent_auth/urls.py
from django.urls import path
from .views import *

app_name = 'toysrent_auth'

urlpatterns = [
    path('register/', register, name = 'register'),
    path('login/', login, name = 'login'),

]

toysrent_auth/models.py
from django.db import models

# Create your models here.

toysrent_auth/forms.py
from django import forms

class SingleFieldForm(forms.Form):
    single_char_field = forms.CharField(label = "", max_length = 50, widget = forms.TextInput(
        attrs = {
            'class': 'form-field',
            'placeholder': '',
            'required': True,
        }
    ))
    
    date_field = forms.DateField(widget = forms.DateInput(
        attrs = {
            'class': 'form-field datepicker',
            'placeholder': '',
            'required': True,
        }
    ))

    date_field_2 = forms.DateField(widget = forms.DateInput(
        attrs = {
            'class': 'form-field datepicker2',
            'placeholder': '',
            'required': True,
        }
    ))
    

toysrent_auth/views.py
from datetime import datetime
from django.db import connection
from django.http import JsonResponse
from django.shortcuts import render
from .forms import SingleFieldForm
from item.models import Kategori
import psycopg2
import json

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def get_admins():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.admin natural join toys_rent.pengguna")
        return control.fetchall()

def get_members():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.anggota natural join toys_rent.pengguna")
        return control.fetchall()

def get_addresses():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.alamat")
        return control.fetchall()

def get_categories():
    with connection.cursor() as control:
        control.execute("select * from toys_rent.kategori")
        return dictfetchall(control)

def register(req):
    req.session.flush()
    flags = {'id_exist': False, 'email_exist': False}

    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)
        
        idn = data['global_data'][0]
        name = data['global_data'][1]
        email = data['global_data'][2]
        bdate = datetime.strptime(data['global_data'][3], "%m/%d/%Y")
        telp = data['global_data'][4]

        if data['role'] == "Admin":
            admins = get_admins()
            for admin in admins:
                if idn in admin:
                    flags['id_exist'] = True
                    return JsonResponse(flags)
                
                if email in admin:
                    flags['email_exist'] = True
                    return JsonResponse(flags)
            
            with connection.cursor() as control:
                control.execute("insert into toys_rent.pengguna(no_ktp, nama_lengkap, email, tanggal_lahir, no_telp)" +
                                "values(%s, %s, %s, %s, %s)", (idn, name, email, bdate, telp,))
                control.execute("insert into toys_rent.admin(no_ktp) values (%s)", (idn,))

                return JsonResponse(flags)
        else:
            members = get_members()
            addresses = data['global_data'][5]

            for member in members:
                if idn in member:
                    flags['id_exist'] = True
                    return JsonResponse(flags)
                
                if email in member:
                    flags['email_exist'] = True
                    return JsonResponse(flags)
            
            with connection.cursor() as control:
                control.execute("insert into toys_rent.pengguna(no_ktp, nama_lengkap, email, tanggal_lahir, no_telp)" +
                                "values(%s, %s, %s, %s, %s)", (idn, name, email, bdate, telp,))
                control.execute("insert into toys_rent.anggota(no_ktp, poin, level) values (%s, %s, %s)", (idn, 0, "BRONZE",))

                for address in addresses:
                    control.execute("insert into toys_rent.alamat(no_ktp_anggota, nama, jalan, nomor, kota, kodepos)" +
                                    "values(%s, %s, %s, %s, %s, %s)", (idn, address[0], address[1], int(address[2]), address[3], address[4],))
                return JsonResponse(flags)
                     
    else:
        form_register_pengguna = SingleFieldForm()
        return render(req, 'register.html', {'form_register_pengguna' : form_register_pengguna, 'admins' : get_admins()})

def init_categories():
    categories = get_categories()

    for category in categories:
        kategori = Kategori()
        kategori.nama = category['nama']
        kategori.level = int(category['level'])
        kategori.save()

def login(req):
    req.session.flush()
    flags = {'id_exist': False, 'mismatch': True, 'is_admin': False}

    if req.method == 'POST' and req.is_ajax():
        init_categories()
        data = json.loads(req.body)
        admins = get_admins()
        members = get_members()

        idn = data['global_login'][0]
        email = data['global_login'][1]

        for admin in admins:
            if idn in admin:
                flags['id_exist'] = True
                flags['is_admin'] = True
                if email in admin:
                    flags['mismatch'] = False
                    req.session['role'] = "admin"
                    req.session['idn'] = idn
                return JsonResponse(flags)

        for member in members:
            if idn in member:
                flags['id_exist'] = True
                if email in member:
                    flags['mismatch'] = False
                    req.session['role'] = "member"
                    req.session['idn'] = idn
                return JsonResponse(flags)
        return JsonResponse(flags)

    else:
        form_login = SingleFieldForm()
        return render(req, 'login.html', {'form_login' : form_login})

toysrent_auth/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login ToysRent</title>
    <link rel = "stylesheet" href = "{% static 'toysrent_auth/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src = "{% static 'toysrent_auth/js/scripts.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'toysrent_auth/js/accordion.js' %}" type = "text/javascript"></script>
</head>
<body class = "main bg-light">
    <div class = "container">
        <div class = "banner">
            <h1 class = "title display-4">ToysRent</h1>
            <p class = "lead desc">Sewa mainan dan aksesoris untuk anak anda.</p>
            <hr class="my-4">
        </div>
        <div class = "login-area">
            <div class = "child">
                <h3>Login</h3>
                <p>Sudah punya akun? Masukkan E-mail dan No. KTP anda untuk mulai meminjam.</p>
                <div class="form-nav">
                    <h6 class = "form-nav-item 1 active">No KTP</h6>
                    <h6 class = "form-nav-item-arrow">></h6>
                    <h6 class = "form-nav-item 2" value="final">E-mail</h6>
                </div>
                <form method="POST", action="", class = "login-form" id = "form-1">
                    {% csrf_token %}
                    {{ form_login.single_char_field }}
                    <button onClick="submitActionLogin(this)" type="submit" class="next-button">></button>
                </form>
                <h6 class = "warn-msg" style = "display:none"></h6>
                <h6 class = "reg-message">Belum punya akun? Daftar <a href = "{% url 'toysrent_auth:register' %}">sekarang</a>.</h6>
            </div>
        </div>
    </div>
</body>
<script>
    $(document).ready(function() {

        $('.form-field:visible').attr("placeholder", $('.active:visible').text());
        $('.active').css("color",    "#007bff");    
    });
</script>
</html>

toysrent_auth/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Daftar Pengguna ToysRent</title>
    <link rel = "stylesheet" href = "{% static 'toysrent_auth/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src = "{% static 'toysrent_auth/js/scripts.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'toysrent_auth/js/accordion.js' %}" type = "text/javascript"></script>

</head>
<body class = "main bg-light">
    <div class = "container">
        <div class = "banner">
            <h1 class = "title display-4">ToysRent</h1>
            <p class = "lead desc">Sewa mainan dan aksesoris untuk anak anda.</p>
            <hr class="my-4">
        </div>
        <div class = "login-area">
            <div class = "child">
                <h3>Daftar Pengguna</h3>
                <p>Daftar untuk menjadi pengguna tetap ToysRent:</p>
                <div class="dropdown">
                    <button class="btn btn-outline-dark btn-sm dropdown-toggle" type="button" id="role-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Pilih role anda
                    </button>
                    <div class="dropdown-menu" aria-labelledby="role-dropdown">
                        <button class="dropdown-item" type="button" id="role-admin">Admin</button>
                        <button class="dropdown-item" type="button" id="role-anggota">Anggota</button>
                    </div>
                </div>
                <div class = "reg-content" id="reg-content-admin" style="display:none">
                    <div class="form-nav">
                        <h6 class = "form-nav-item 1 active">No KTP</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 2">Nama Lengkap</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 3">E-mail</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 4">Tanggal Lahir</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 5" value = "final">Nomor Telepon</h6>
                    </div>
                    <form method="POST", action="", class = "login-form">
                        {% csrf_token %}
                        {{ form_register_pengguna.single_char_field }}
                        {{ form_register_pengguna.date_field }}
                        <button onClick="submitActionRegister(this)" type="submit" class="next-button">></button>
                    </form>
                </div>
                <div class = "reg-content" id="reg-content-anggota" style="display:none">
                    <div class="form-nav">
                        <h6 class = "form-nav-item 1 active">No KTP</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 2">Nama Lengkap</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 3">E-mail</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 4">Tanggal Lahir</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 5">Nomor Telepon</h6>
                        <h6 class = "form-nav-item-arrow">></h6>
                        <h6 class = "form-nav-item 6" value = "final">Alamat</h6>
                    </div>
                    <form method="POST", action="", class = "login-form last-address" id = "form-1">
                        <button onClick="addAddress()"  type="button" class="next-button plus-button" style="display:none">+</button>
                        {% csrf_token %}
                        {{ form_register_pengguna.single_char_field }}
                        {{ form_register_pengguna.date_field_2 }}
                        <div class = "alamat" id = "nama" style="display:none">
                            {{ form_register_pengguna.single_char_field }}
                        </div>
                        <div class = "alamat" id = "jalan" style="display:none">
                            {{ form_register_pengguna.single_char_field }}
                        </div>
                        <div class = "alamat" id = "nomor" style="display:none">
                            {{ form_register_pengguna.single_char_field }}
                        </div>
                        <div class = "alamat" id = "kota" style="display:none">
                            {{ form_register_pengguna.single_char_field }}
                        </div>
                        <div class = "alamat" id = "kodepos" style="display:none">
                            {{ form_register_pengguna.single_char_field }}
                        </div>
                        <button onClick="submitActionRegister(this)" type="submit" class="next-button" id = "nexty">></button>
                    </form>
                </div>
                <h6 class = "warn-msg" style = "display:none">Nomor KTP atau E-mail yang anda masukkan sudah pernah terdaftar.</h6>
                <h6 class = "reg-message"><a href = "{% url 'toysrent_auth:login' %}">Saya sudah pernah mendaftar</a>.</h6>
                <button type="button" id = "success-reg" data-toggle="modal" data-target="#reg-continue" style="display: none"></button>
                <div class="modal fade" id="reg-continue" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ModalTitle">Anda telah terdaftar!</h5>
                        </div>
                        <div class="modal-body">
                            Selamat! Anda telah terdaftar sebagai pengguna.
                        </div>
                        <div class="modal-footer">
                            <a href = "{% url 'toysrent_auth:login' %}"><button type="button" class="btn btn-outline-primary">Login</button></a>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    $(document).ready(function() {
        $( ".datepicker" ).datepicker({
            changeMonth: true,
            changeYear: true
        });
        $( ".datepicker2" ).datepicker({
            changeMonth: true,
            changeYear: true
        });

        $('.hasDatepicker').hide();
        $('.active').css("color", "#007bff");    
    });
</script>
</html>